# Site settings
title: AshGillman.github.io
email: gillmanash@gmail.com
description: >
  Tidbits I've learned and shared.
url: http://ashgillman.github.io
twitter_username: AshleyGillman
github_username:  ashgillman

footer-links:
  github: ashgillman
  email: gillmanash@gmail.com
  twitter: AshleyGillman
  stackoverflow: users/3903368/gilly

# Build settings
markdown: kramdown

sass:
  style: expanded

exclude:
  - "*.org"
  - "*.bib"

plugins:
  - github-pages
  - jekyll_github_sample

dev: 0

encoding: utf-8